apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-deploy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: getintodevops-hellonode
          imagePullPolicy: Always
          image: nexus.sysdata.it:18000/getintodevops-hellonode:latest
          ports:
          - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
      imagePullSecrets:
        - name: sysnexus
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: demo
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demo-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: demo-deploy
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 50
